databases:
  - name: tienda-db
    plan: free

services:
  - type: web
    name: tienda
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tienda-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: 0
      - key: ALLOWED_HOSTS
        value: "tienda.onrender.com"